TextOutput                      	PROTO	:DWORD
clrOutput                       	PROTO
HexOutput                       	PROTO	:DWORD
DllEntry                        	PROTO	:HINSTANCE,:DWORD,:DWORD
AddMenu                         	PROTO	:DWORD,:DWORD
LoadSettingsFromProjectFile     	PROTO
SaveSettingsToProjectFile       	PROTO
InstallDll                      	PROTO	:DWORD,:DWORD
ProtoProc                       	PROTO	:HWND,:UINT,:WPARAM,:LPARAM
CreateProtoLine                 	PROTO	:DWORD,:DWORD,:DWORD
SaveToFile                      	PROTO
LoadIntoLstBox                  	PROTO
SendToOutput                    	PROTO
DllProc                         	PROTO	:HWND,:UINT,:WPARAM,:LPARAM
