.486
.model flat, stdcall  ; 32 bit memory model
option casemap :none  ; case sensitive

include RadASMI.inc
include Mdi\Misc.asm
include Mdi\Unicode.asm
include Api\WordList.asm
include Api\ApiCall.asm
include Api\ApiType.asm
include Api\ApiConst.asm
include Api\ApiStruct.asm
include Api\ApiWord.asm
include Api\ApiMessage.asm
include Edit\FileTime.asm
include Tools\Tools.asm
include Opt\FontOption.asm
include Ini\IniFile.asm
include Ctls\Toolbar.asm
include Ctls\Statusbr.asm
include Prp\Parse.asm
include Edit\ProFind.asm
include Edit\Find.asm
include Pro\ProjectScan.asm
include Edit\AddVar.asm
include Hex\HexEdit.asm
include Edit\Edit.asm
include Edit\EditOption.asm
include Prnt\PrintOption.asm
include Prnt\Print.asm
include Edit\KeyWords.asm
include Edit\CodeWrite.asm
include Edit\SnipletOption.asm
include Opt\FolderOption.asm
include Opt\MenuOption.asm
include Opt\FileBrowser.asm
include Opt\ExternalFile.asm
include Dlg\DlgEdit.asm
include Edit\Accelerator.asm
include Edit\Resource.asm
include Edit\StringTable.asm
include Dlg\DlgOption.asm
include Mnu\MenuEdit.asm
include Ver\Verinfo.asm
include Edit\Language.asm
include Pro\Project.asm
include Pro\ProjectGroups.asm
include Edit\MainFiles.asm
include Pro\ProOption.asm
include Out\Output.asm
include Tpl\CreateTpl.asm
include ToolBox\ToolBox.asm
include Prp\Property.asm
include Tab\TabTool.asm
include Tools\InfoTool.asm
include Wiz\Wizard.asm
include Edit\ExportID.asm
include Edit\Sniplets.asm
include Dib\ShowDib.asm
include Mac\Macro.asm
include Tools\ToolOptions.asm
include Opt\AccelOption.asm
include Opt\FileAssociation.asm
include Mdi\About.asm
include Block\Block.asm
include Opt\LanguageOption.asm
include Opt\ProgLanguage.asm
include Opt\CustomControls.asm
include Opt\Environment.asm
include Mdi\MdiRadAsm.asm
